# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: Button
  description: Button
  icon: 'button'
  tags: ['global', 'button']

# Defines the structure of this component, as well as the default values
blueprint:
  path:
  button_text:
  button_text_color:
  button_color:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
